---
swagger: "2.0"
info:
  description: "RIHA-Browser API documentation"
  version: "1.0"
  title: "RIHA-Browser API"
  license:
    name: "MIT"
basePath: "/"
tags:
- name: "Environment configuration"
- name: "Information systems"
- name: "Users"
schemes:
- "http"
paths:
  /api/v1/environment:
    get:
      tags:
      - "Environment configuration"
      summary: "Retrieve environment"
      description: ""
      operationId: "environment"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /api/v1/environment/organization:
    put:
      tags:
      - "Environment configuration"
      summary: "Change active organization of the current user"
      description: ""
      operationId: "changeActiveOrganization"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "string"
      responses:
        default:
          description: "successful operation"
      deprecated: true
  /api/v1/systems:
    get:
      tags:
      - "Information systems"
      summary: "List all existing information systems"
      description: ""
      operationId: "list"
      parameters:
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      - name: "filter"
        in: "query"
        description: "filter options"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        description: "sorting options"
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: "field list"
        required: false
        type: "string"
      responses:
        default:
          description: "successful operation"
    post:
      tags:
      - "Information systems"
      summary: "Create new information system"
      description: ""
      operationId: "create"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/InfoSystemModel"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/InfoSystemModel"
  /api/v1/systems/{shortName}:
    get:
      tags:
      - "Information systems"
      summary: "Get existing information system"
      description: ""
      operationId: "get"
      parameters:
      - name: "shortName"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/InfoSystemModel"
    put:
      tags:
      - "Information systems"
      summary: "Update existing information system"
      description: ""
      operationId: "update"
      parameters:
      - name: "shortName"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/InfoSystemModel"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/InfoSystemModel"
  /api/v1/user:
    get:
      tags:
      - "Users"
      summary: "Retrieves user details"
      description: ""
      operationId: "getUserDetails"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserDetailsModel"
  /api/v1/user/organization:
    put:
      tags:
      - "Users"
      summary: "Change active organization of the current user"
      description: ""
      operationId: "changeActiveOrganization"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "string"
      responses:
        default:
          description: "successful operation"
definitions:
  InfoSystemModel:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      details:
        type: "string"
  OrganizationModel:
    type: "object"
    properties:
      code:
        type: "string"
      name:
        type: "string"
  UserDetailsModel:
    type: "object"
    properties:
      personalCode:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      organizations:
        type: "array"
        items:
          $ref: "#/definitions/OrganizationModel"
      activeOrganization:
        $ref: "#/definitions/OrganizationModel"
      roles:
        type: "array"
        items:
          type: "string"
